### ISSUE TITLE
Password encoding

### ISSUE THREAD

**Issue by fschreiterer** [eduMFA/eduMFA#187]
### Top-level intent

Password is not right encoded with local checkpin

### Steps to reproduce

1. Set local checkpin for an remote token
2. Set a password with % - maybe other special sign may also break password check
3. Try to login with password an OTP and an it fails

### Expected outcome

What do you think, how the system should have worked?

### Actual outcome
Please fix encoding and never show cleartextpassword in Logfile

What did actually happen?

### Configuration

* **eduMFA version**: 2.0.3
* **Installation method**: (from Ubuntu packages, github, PyPI, ...) venv
* **Python version**: 3.11
* **Operating system**: ubuntu 22.04
* **Webserver**: apache
* **Token database**: (MySQL, PostgreSQL, ...) Mariadb

### Log file

**Set EDUMFA_LOGLEVEL = logging.DEBUG in edumfa.cfg and take a look at the edumfa.log!**
**If appropriate, attach the log file or paste relevant portions.**
[INFO][edumfa.lib.eventhandler.tokenhandler:568] Action change failcounter requires serial number. But no serial number could be found in request <Request 'http://127.0.0.1/validate/check?user=USERID&realm=REALM&pass=somesigns%somesigns' [GET]>.
[INFO][edumfa.lib.user:420] User 'USERID' from realm 'REALM' tries to authenticate
[WARNING][edumfa.lib.resolvers.LDAPIdResolver:368] failed to check password for 'USERID'/'cn=USERID,dc=uni-bamberg,dc=de': Exception('Wrong credentials')
[INFO][edumfa.lib.user:432] user User(login='USERID', realm='REALM', resolver='RESOLVERNAME') failed to authenticate.

**Comment by fritterhoff** [comment]
Hi Frank,

well, at some point I would say works as designed. 
Anyway, I will check which options `Flask` provides us to avoid such encoding problems but I assume that at least some special characters like a `&` will always cause some strange behavior. e.g. a request `http://127.0.0.1/validate/check?user=USERID&pass=somesigns%somesigns&realm=REALM` can be read as 
`user: USERID, pass: somesigns%somesigns&realm=REALM`
or `user: USERID, pass: somesigns%somesigns, realm: REALM`

I have not checked yet but from my experience using encoded params like `somesigns%25somesigns` could work? 🤔 

Regarding the log: I will check how we can disable logging the password but I am pretty sure that the same requests are also logged in the apache?

In general I strongly recommend to use `POST` Requests where possible since they don't cause these problems

Flo

**Comment by fschreiterer** [comment]
It is an wrong local request and not e problem in eduMFA. Sorry

**Comment by fschreiterer** [comment]
It is an wrong local request and not e problem in eduMFA. Sorry
