### ISSUE TITLE
Set custom attribute doesn't seem to work?

### ISSUE THREAD

**Issue by oculos** [eduMFA/eduMFA#380]
### Top-level intent

What did you try to achieve?

I tried to add a custom attribute to a user, as an admin. 

### Steps to reproduce

1. Add attribute 
2. Get an error:
<img width="469" alt="Screenshot 2024-10-21 at 20 01 55" src="https://github.com/user-attachments/assets/2c885da3-2feb-45f2-9943-b985c24f9ee6">

### Expected outcome

Being able to add an attribute

So what happens is that I go ahead and add an admin policy, so that the set_user_attributes could be performed. But when I first add an admin policy, so it seems that the admin looses all his rights, except that one. I had to go to the database and delete the policy.

Does an admin really need that policy and, if so, how to add it without loosing all the native admin rights?

**Comment by fritterhoff** [comment]
Well. We prop. have to differ between two things. 

 - Adding a custom attribute requires defining the attribute before using a policy -> Adding attribute 'None' as shown in the image will trigger an error. Maybe there is an option to prevent this in the UI
 - The observed flow that you get sort of locked out as an admin is in general also the expected behavior. The admin policies are used to limit the admin functionalities. So yes, prop. you must define a policy allowing custom attributes + all other actions.
