### ISSUE TITLE
Packaging eduMFA for openSUSE: Specify minimum versions instead of exact version constraints?

### ISSUE THREAD

**Issue by kastl-ars** [eduMFA/eduMFA#464]
Dear maintainers,

I am trying to package eduMFA for openSUSE. One thing I came across while trying are the dependencies.

## Version constraints

The ` requirements.txt` file as well as the `pyproject.toml` put exact version constraints on the dependencies. While this is great for reproducibility of tests, it is not maintainable in a distribution. If a security flaw is found in a package, it is being updated.

Would it be possible to specify the minimum required version? Or the range, if there is an upper boundary (`foo >= 1.2.0 <2`). This way, newer versions (within that range) can be used while still making sure all required features are present?

I know this is asking a lot, but it would make it possible to package eduMFA reliably...

Kind Regards,
Johannes

**Comment by fritterhoff** [comment]
Hi,

Well. We at least try to stick to the latest versions of the dependencies. From my experience, in general the problem is that the distributions provide older versions than pypi so we recommend to install the versions in a venv and don't stick to os versions. 

I don't think we can manage to support other versions at the moment, but i will discuss it with the remaining team.

Flo

**Comment by kastl-ars** [comment]
Thank you very much for taking this into consideration, Florian!

**Comment by fritterhoff** [comment]
So. We have discussed this internally and currently see no option to support it in this way. We consider it best practice to install based on pypi in a venv and will continue to maintain the constraints in this way until further notice.

**Comment by kastl-ars** [comment]
Thank you very much for discussing. If it is not feasible, then so be it.

Have a nice weekend.
